# Generated by Django 3.1.7 on 2021-07-14 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boleta_numero', models.IntegerField(verbose_name='Boleta N°...')),
                ('fecha_atencion', models.DateTimeField(blank=True, verbose_name='Fecha de atencion')),
                ('documento', models.CharField(blank=True, max_length=10)),
                ('descuento', models.IntegerField(verbose_name='Descuento a realizar')),
            ],
        ),
        migrations.CreateModel(
            name='BoletaServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_total', models.IntegerField(verbose_name='Sub-Total de la atencion')),
                ('total', models.IntegerField(verbose_name='Total operaciones')),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boleta.boleta', verbose_name='Boleta Cabecera')),
            ],
            options={
                'verbose_name': 'Detalle',
                'verbose_name_plural': 'Detalles',
            },
        ),
    ]
