# Generated by Django 3.1.7 on 2021-07-12 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BoletaServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad de productos')),
                ('valor_total', models.IntegerField(verbose_name='Valor total productos')),
                ('fecha_atencion', models.DateTimeField(blank=True, verbose_name='Fecha de atencion')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.almacen', verbose_name='almacen')),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boleta.boleta', verbose_name='boleta')),
            ],
            options={
                'verbose_name': 'Detalle',
                'verbose_name_plural': 'Detalles',
            },
        ),
    ]
