# Generated by Django 3.1.7 on 2021-05-26 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='boletaServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_unitario', models.IntegerField(verbose_name='Valor por unidad')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad de productos')),
                ('valor_total', models.IntegerField(verbose_name='Valor total productos')),
                ('fecha_atencion', models.DateTimeField(blank=True, verbose_name='Fecha de atencion')),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boleta.boleta', verbose_name='boleta')),
                ('servicios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicios')),
            ],
            options={
                'verbose_name': 'Detalle',
                'verbose_name_plural': 'Detalles',
            },
        ),
    ]
