# Generated by Django 3.1.7 on 2021-06-13 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_auto_20210613_0418'),
        ('boleta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletaservicio',
            name='procedimiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documentos.procedimientos', verbose_name='Procedimiento paciente'),
            preserve_default=False,
        ),
    ]
