# Generated by Django 3.1.7 on 2021-07-12 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
        ('configuracion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boleta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boleta',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.empresa'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='serviciosList',
            field=models.ManyToManyField(to='servicios.ServiciosList'),
        ),
    ]
