# Generated by Django 3.1.7 on 2021-06-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_auto_20210614_2153'),
        ('boleta', '0002_boletaservicio_procedimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boletaservicio',
            name='servicios',
        ),
        migrations.AddField(
            model_name='boletaservicio',
            name='serviciosList',
            field=models.ManyToManyField(to='servicios.ServiciosList'),
        ),
    ]
