# Generated by Django 3.1.7 on 2021-07-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boleta', '0002_auto_20210714_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletaservicio',
            name='sub_total',
            field=models.IntegerField(null=True, verbose_name='Sub-Total de la atencion'),
        ),
        migrations.AlterField(
            model_name='boletaservicio',
            name='total',
            field=models.IntegerField(null=True, verbose_name='Total operaciones'),
        ),
    ]
