# Generated by Django 3.1.7 on 2021-06-15 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boleta', '0004_auto_20210614_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boletaservicio',
            name='procedimiento',
        ),
    ]
