# Generated by Django 3.1.7 on 2021-06-15 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0005_almacen_valor_unitario'),
        ('boleta', '0005_remove_boletaservicio_procedimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boletaservicio',
            name='valor_unitario',
        ),
        migrations.AddField(
            model_name='boletaservicio',
            name='almacen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='almacen.almacen', verbose_name='almacen'),
            preserve_default=False,
        ),
    ]
