# Generated by Django 3.1.7 on 2021-05-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(blank=True, choices=[('0', 'LIQUIDACION'), ('1', 'FINIQUITO'), ('2', 'AFP')], max_length=1)),
                ('valor', models.CharField(blank=True, max_length=250)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Documento', verbose_name='Imagen 1')),
            ],
            options={
                'verbose_name': 'Documento cargado',
                'verbose_name_plural': 'Documentos cargados',
            },
        ),
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfermedad', models.CharField(blank=True, choices=[('S', 'SI'), ('N', 'NO')], max_length=1)),
                ('alergia', models.CharField(blank=True, choices=[('S', 'SI'), ('N', 'NO')], max_length=1)),
                ('enfermedades', models.TextField(blank=True, max_length=250)),
                ('alergias', models.TextField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': 'Ficha tecnica',
            },
        ),
        migrations.CreateModel(
            name='Procedimientos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_procedimientos', models.DateField(blank=True, null=True, verbose_name='Fecha del procedimiento')),
                ('tipo_procedimiento', models.CharField(blank=True, choices=[('0', 'FRENILLOS'), ('1', 'REVISON'), ('2', 'TAPADURA'), ('3', 'EXTRACCION'), ('4', 'CORONA'), ('5', 'TRATAMIENTO CONDUCTO')], max_length=1)),
                ('descripcion_procedimiento', models.TextField(blank=True, max_length=250, verbose_name='Descripcion de o los procedimientos')),
            ],
            options={
                'verbose_name_plural': 'Procedimientos',
            },
        ),
    ]
