# Generated by Django 3.1.7 on 2021-07-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_auto_20210714_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='valor',
            field=models.IntegerField(blank=True, max_length=250),
        ),
    ]
