# Generated by Django 3.1.7 on 2021-06-08 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documentos', '0002_documento_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='users',
        ),
        migrations.AddField(
            model_name='documento',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prod_created', to='users.user'),
            preserve_default=False,
        ),
    ]
