# Generated by Django 3.1.7 on 2021-06-13 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documentos', '0003_auto_20210608_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichatecnica',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procedimientos',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='cliente y especialista'),
            preserve_default=False,
        ),
    ]
