# Generated by Django 3.1.7 on 2021-07-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_auto_20210714_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='valor',
            field=models.IntegerField(blank=True, verbose_name='Valor del documento'),
        ),
    ]
