# Generated by Django 3.1.7 on 2021-06-17 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documentos', '0004_auto_20210613_0418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='user',
        ),
        migrations.AddField(
            model_name='documento',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documento',
            name='documento',
            field=models.CharField(blank=True, choices=[('0', 'LIQUIDACION'), ('1', 'FINIQUITO'), ('2', 'AFP')], max_length=100),
        ),
        migrations.AlterField(
            model_name='documento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Documento', verbose_name='Imagen'),
        ),
    ]
