# Generated by Django 3.1.7 on 2021-07-12 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documentos', '0005_auto_20210617_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimientos',
            name='fecha_procedimientos',
        ),
        migrations.AlterField(
            model_name='procedimientos',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='procedimientos',
            name='tipo_procedimiento',
            field=models.CharField(blank=True, choices=[('0', 'Odontologo General'), ('1', 'Ortodoncista'), ('2', 'Radiologo'), ('3', 'Prostodoncista')], max_length=1),
        ),
        migrations.CreateModel(
            name='EspecialistaProcedimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
        ),
        migrations.AddField(
            model_name='procedimientos',
            name='Especialista_Procedimiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documentos.especialistaprocedimiento'),
            preserve_default=False,
        ),
    ]
