# Generated by Django 3.1.7 on 2021-07-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiciosList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=120, unique=True, verbose_name='servicio prestado')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios prestados',
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, verbose_name='paquete de servicio')),
                ('valor_paquete', models.IntegerField(blank=True, verbose_name='Valor paquete')),
                ('servicios_lista', models.ManyToManyField(to='servicios.ServiciosList')),
            ],
        ),
    ]
