# Generated by Django 3.1.7 on 2021-07-12 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicios',
            old_name='servicios_lista',
            new_name='serviciosList',
        ),
    ]
