# Generated by Django 3.1.7 on 2021-06-13 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicios', '0002_servicioslist_especialista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='name',
            field=models.CharField(blank=True, max_length=25, verbose_name='servicios por especialidad'),
        ),
        migrations.AlterField(
            model_name='servicioslist',
            name='especialista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='especialista '),
        ),
    ]
