# Generated by Django 3.1.7 on 2021-07-12 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20210712_0411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicios',
            old_name='serviciosList',
            new_name='servicios_lista',
        ),
    ]
