# Generated by Django 3.1.7 on 2021-06-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_auto_20210613_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioslist',
            name='servicio',
            field=models.CharField(max_length=120, unique=True, verbose_name='Servicio'),
        ),
    ]
