# Generated by Django 3.1.7 on 2021-06-15 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_auto_20210614_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicios',
            old_name='servicios',
            new_name='ServiciosList',
        ),
    ]
