# Generated by Django 3.1.7 on 2021-06-15 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_auto_20210614_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicios',
            old_name='ServiciosList',
            new_name='serviciosList',
        ),
    ]
