# Generated by Django 3.1.7 on 2021-06-15 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_auto_20210614_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicioslist',
            name='especialista',
        ),
    ]
