# Generated by Django 3.1.7 on 2021-06-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_remove_servicioslist_especialista'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioslist',
            name='valor',
            field=models.IntegerField(blank=True, default=1, verbose_name='valor por servicio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicioslist',
            name='servicio',
            field=models.CharField(max_length=120, unique=True, verbose_name='servicio prestado'),
        ),
    ]
