# Generated by Django 3.1.7 on 2021-06-16 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0008_auto_20210615_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicioslist',
            name='valor',
        ),
        migrations.AddField(
            model_name='servicios',
            name='valor_paquete',
            field=models.IntegerField(blank=True, default=1, verbose_name='Valor paquete'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicios',
            name='name',
            field=models.CharField(blank=True, max_length=25, verbose_name='paquete de servicio'),
        ),
    ]
