# Generated by Django 3.1.7 on 2021-06-17 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0010_servicios_almacen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='almacen',
        ),
    ]
