# Generated by Django 3.1.7 on 2021-06-20 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0012_auto_20210617_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicios',
            old_name='servicios_listar',
            new_name='servicios_lista',
        ),
    ]
