# Generated by Django 3.1.7 on 2021-06-18 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuracion', '0004_auto_20210616_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(blank=True, max_length=25, verbose_name='Nombre del producto')),
                ('descripcion', models.CharField(blank=True, max_length=50, verbose_name='Descripcion del producto')),
                ('cantidad', models.PositiveIntegerField(blank=True, verbose_name='Cantidad por producto')),
                ('precio_unitario', models.PositiveIntegerField(verbose_name='Precio unitario del producto')),
                ('total', models.PositiveIntegerField(blank=True, default=True, null=True, verbose_name='Total del producto')),
            ],
            options={
                'verbose_name': 'Detalles de la compra',
            },
        ),
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalles_recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.detalles', verbose_name='Detalles del pedido recepcionado')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Receptor de los productos')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha compra')),
                ('linda_sonrisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.empresa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.moneda')),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fecha de la orden de compra',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estados', models.CharField(blank=True, choices=[('0', 'PROCESANDO'), ('1', 'PREPARANDO'), ('2', 'DESPACHADO'), ('3', 'ENCAMINO'), ('4', 'ENTREGADO'), ('5', 'FINALIZADO')], max_length=1)),
                ('observacion', models.TextField(max_length=250, verbose_name='Observaciones')),
                ('detalles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.detalles')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='proveedor da reporte')),
            ],
            options={
                'verbose_name': 'Estados del producto',
            },
        ),
        migrations.AddField(
            model_name='detalles',
            name='ordenes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.orden'),
        ),
    ]
