# Generated by Django 3.1.7 on 2021-06-19 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recepcion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado',
            name='detalles',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='linda_sonrisa',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='moneda',
        ),
        migrations.AddField(
            model_name='estado',
            name='orden',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recepcion.orden', verbose_name='identificador tipo de orden'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='name',
            field=models.CharField(blank=True, max_length=25, verbose_name='Nombre de la orden'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='observacion',
            field=models.TextField(max_length=100, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='recepcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Recepcionista del pedido'),
        ),
    ]
