# Generated by Django 3.1.7 on 2021-07-18 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0002_auto_20210714_0134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recepcion',
            options={'verbose_name': '3- Recepcion de productos', 'verbose_name_plural': '3- Recepcion de los productos'},
        ),
    ]
