# Generated by Django 3.1.7 on 2021-06-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0002_auto_20210619_0659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estado',
            old_name='proveedor',
            new_name='proveedores',
        ),
        migrations.AddField(
            model_name='orden',
            name='proveedor',
            field=models.CharField(blank=True, max_length=50, verbose_name='email-proveedor'),
        ),
    ]
