# Generated by Django 3.1.7 on 2021-06-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0003_auto_20210619_0705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalles',
            options={'verbose_name': '2- Detalles de las compra'},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'verbose_name': '4- Estados del producto', 'verbose_name_plural': '4- Estados de los productos'},
        ),
        migrations.AlterModelOptions(
            name='orden',
            options={'verbose_name': '1- Orden N°'},
        ),
        migrations.AlterModelOptions(
            name='recepcion',
            options={'verbose_name': '3- Recepcion de productos', 'verbose_name_plural': '4- Recepcion de los productos'},
        ),
        migrations.AlterField(
            model_name='estado',
            name='estados',
            field=models.CharField(blank=True, choices=[('PROCESANDO', 0), ('PREPARANDO', 1), ('DESPACHADO', 2), ('ENCAMINO', 3), ('ENTREGADO', 4), ('FINALIZADO', 5)], max_length=25),
        ),
    ]
