# Generated by Django 3.1.7 on 2021-06-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0004_auto_20210619_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='estados',
            field=models.CharField(blank=True, choices=[('0', 'PROCESANDO'), ('1', 'PREPARANDO'), ('2', 'DESPACHADO'), ('3', 'ENCAMINO'), ('4', 'ENTREGADO'), ('5', 'FINALIZADO')], max_length=1),
        ),
    ]
