# Generated by Django 3.1.7 on 2021-06-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0005_auto_20210620_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='estados',
            field=models.CharField(blank=True, choices=[('0', 'Procesando'), ('1', 'Preparando'), ('2', 'Despachado'), ('3', 'Encamino'), ('4', 'Entregado'), ('5', 'Finalizado')], max_length=1),
        ),
    ]
