# Generated by Django 3.1.7 on 2021-06-21 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recepcion', '0006_auto_20210621_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='detalles',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Proveedor del pedido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estado',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.orden', unique=True, verbose_name='identificador tipo de orden'),
        ),
    ]
