# Generated by Django 3.1.7 on 2021-06-22 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recepcion', '0007_auto_20210621_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalles',
            name='codigo',
            field=models.CharField(blank=True, max_length=17, verbose_name='codigo del producto'),
        ),
        migrations.AddField(
            model_name='detalles',
            name='familia',
            field=models.CharField(blank=True, max_length=50, verbose_name='tipo producto'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='valido',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orden',
            name='recepcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Solicitante'),
        ),
    ]
