# Generated by Django 3.1.7 on 2021-06-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0008_auto_20210622_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalles',
            name='proveedor',
            field=models.EmailField(blank=True, max_length=254, verbose_name='emial del proveedor'),
        ),
    ]
