# Generated by Django 3.1.7 on 2021-06-22 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recepcion', '0009_auto_20210622_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalles',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha vencimiento'),
        ),
        migrations.AlterField(
            model_name='detalles',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Proveedor del producto'),
        ),
    ]
