# Generated by Django 3.1.7 on 2021-06-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0010_auto_20210622_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalles',
            name='proveedor',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email proveedor'),
        ),
    ]
