# Generated by Django 3.1.7 on 2021-06-22 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0008_auto_20210619_0659'),
        ('recepcion', '0011_auto_20210622_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcion',
            name='almacen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='almacen.almacen', verbose_name='ALMACEN ACTUALIZAR PRODUCTOS'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estado',
            name='orden',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recepcion.orden', verbose_name='identificador tipo de orden'),
        ),
    ]
