# Generated by Django 3.1.7 on 2021-06-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0013_detalles_almacen'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalles',
            name='valid',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
