# Generated by Django 3.1.7 on 2021-06-22 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0012_auto_20210622_1203'),
        ('recepcion', '0014_detalles_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalles',
            name='almacen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.almacen', verbose_name='ALMACEN ACTUALIZAR PRODUCTOS'),
        ),
    ]
