# Generated by Django 3.1.7 on 2021-06-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0015_auto_20210622_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalles',
            name='valid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
