# Generated by Django 3.1.7 on 2021-06-22 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0016_auto_20210622_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalles',
            name='ordenes',
        ),
    ]
