# Generated by Django 3.1.7 on 2021-06-22 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0017_remove_detalles_ordenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalles',
            name='ordenes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recepcion.orden'),
            preserve_default=False,
        ),
    ]
