# Generated by Django 3.1.7 on 2021-07-09 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recepcion', '0018_detalles_ordenes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalles',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Proveedor'),
            preserve_default=False,
        ),
    ]
