# Generated by Django 3.1.7 on 2021-07-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0019_auto_20210708_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalles',
            name='almacen',
        ),
        migrations.RemoveField(
            model_name='recepcion',
            name='almacen',
        ),
        migrations.AlterField(
            model_name='detalles',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, max_length=10, null=True, verbose_name='Fecha vencimiento'),
        ),
    ]
