# Generated by Django 3.1.7 on 2021-07-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0020_auto_20210710_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcion',
            name='agregado',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
