# Generated by Django 3.1.7 on 2021-07-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0021_recepcion_agregado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalles',
            name='recepcionado',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
