# Generated by Django 3.1.7 on 2021-07-11 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0022_detalles_recepcionado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='recepcion',
            new_name='receptor',
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='detalles_recepcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.orden', verbose_name='Ordenes recepcionadas'),
        ),
    ]
