# Generated by Django 3.1.7 on 2021-07-11 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0023_auto_20210711_0019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='receptor',
            new_name='recepcion',
        ),
        migrations.AlterField(
            model_name='recepcion',
            name='detalles_recepcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.detalles', verbose_name='Detalles del pedido recepcionado'),
        ),
    ]
