# Generated by Django 3.1.7 on 2021-07-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('rut', models.CharField(blank=True, max_length=13)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=30, verbose_name='nombre')),
                ('apellido', models.CharField(blank=True, max_length=30, verbose_name='apellidos')),
                ('tipo_usuario', models.CharField(blank=True, choices=[('0', 'Administrador'), ('1', 'Especialista'), ('2', 'Recepcionista'), ('3', 'Cliente'), ('4', 'Proveedor')], max_length=1)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otros')], max_length=1)),
                ('especialidades', models.CharField(blank=True, choices=[('0', 'Odontologo General'), ('1', 'Ortodoncista'), ('2', 'Radiologo'), ('3', 'Prostodoncista')], max_length=1)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('region', models.CharField(blank=True, max_length=25)),
                ('ciudad', models.CharField(blank=True, max_length=30)),
                ('comuna', models.CharField(blank=True, max_length=25)),
                ('direccion', models.CharField(blank=True, max_length=50)),
                ('numero', models.CharField(blank=True, max_length=6, verbose_name='Número de casa')),
                ('contacto', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero de contacto')),
                ('is_esp', models.BooleanField(default=False)),
                ('is_emp', models.BooleanField(default=False)),
                ('is_cli', models.BooleanField(default=False)),
                ('is_pro', models.BooleanField(default=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='User', verbose_name='Avatar Especialista')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuarios registrado',
            },
        ),
    ]
