# Generated by Django 3.1.7 on 2021-05-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='especialidades',
            field=models.CharField(blank=True, choices=[('0', 'Odontologo General'), ('1', 'Ortodoncista'), ('2', 'Radiologo'), ('3', 'Prostodoncista')], max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='rut',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
