# Generated by Django 3.1.7 on 2021-05-26 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210526_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuarios registrado'},
        ),
    ]
