# Generated by Django 3.1.7 on 2021-06-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210526_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contraseña',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
