# Generated by Django 3.1.7 on 2021-06-08 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_contraseña'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contraseña',
        ),
    ]
