# Generated by Django 3.1.7 on 2021-06-16 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0009_auto_20210615_2344'),
        ('users', '0005_remove_user_contraseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='servicios.servicios', verbose_name='servicios para especialista'),
            preserve_default=False,
        ),
    ]
