# Generated by Django 3.1.7 on 2021-06-16 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0009_auto_20210615_2344'),
        ('users', '0006_user_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='servicio',
        ),
        migrations.AddField(
            model_name='user',
            name='servicios',
            field=models.ManyToManyField(to='servicios.Servicios'),
        ),
    ]
