# Generated by Django 3.1.7 on 2021-06-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0009_auto_20210615_2344'),
        ('users', '0007_auto_20210616_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='servicios',
            field=models.ManyToManyField(blank=True, to='servicios.Servicios'),
        ),
    ]
