# Generated by Django 3.1.7 on 2021-06-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210624_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cli',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='esp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pro',
        ),
        migrations.AddField(
            model_name='user',
            name='is_cli',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_emp',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_esp',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_pro',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
