# Generated by Django 3.1.7 on 2021-06-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210627_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contacto',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero de contacto'),
        ),
    ]
