# Generated by Django 3.1.7 on 2021-07-01 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210630_1921'),
        ('users', '0013_auto_20210630_1957'),
    ]

    operations = [
    ]
