# Generated by Django 3.1.7 on 2021-07-11 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_merge_20210701_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='User', verbose_name='Imagen'),
        ),
    ]
