# Generated by Django 3.1.7 on 2021-07-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='User', verbose_name='Avatar Especialista'),
        ),
    ]
