# Generated by Django 3.1.7 on 2021-07-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True, verbose_name='Fecha disponibles')),
                ('hora', models.CharField(max_length=6, null=True, verbose_name='hora ofrecida')),
            ],
            options={
                'verbose_name': 'agenda especialista',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True, verbose_name='Fecha de hora tomada')),
                ('hora', models.CharField(max_length=6, null=True, verbose_name='Hora tomada')),
            ],
        ),
    ]
