# Generated by Django 3.1.7 on 2021-06-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hora', '0002_auto_20210613_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='hora',
            field=models.IntegerField(default=1, verbose_name='hora ofrecida'),
            preserve_default=False,
        ),
    ]
