# Generated by Django 3.1.7 on 2021-06-20 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hora', '0003_agenda_hora'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'verbose_name': 'agenda especialista'},
        ),
    ]
