# Generated by Django 3.1.7 on 2021-06-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hora', '0004_auto_20210620_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='hora',
            field=models.IntegerField(null=True, verbose_name='hora ofrecida'),
        ),
    ]
