# Generated by Django 3.1.7 on 2021-06-20 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hora', '0005_auto_20210620_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='especialista_agenda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agenda del espacialista'),
        ),
    ]
