# Generated by Django 3.1.7 on 2021-06-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hora', '0006_auto_20210620_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='fecha',
            field=models.DateField(null=True, verbose_name='Fecha disponibles'),
        ),
    ]
