from django.db import models
from django.conf import settings
from rest_framework.fields import ReadOnlyField

from applications.almacen.models import Almacen
#
from .managers import ServiciosManager

class ServiciosList(models.Model):
    
    servicio = models.CharField(
        'servicio prestado',
        max_length=120,
        unique=True,
        #editable=False
    ) 

    class Meta:
        verbose_name = 'Servicio'
        verbose_name_plural = 'Servicios prestados'

    def __str__(self):
        return str(self.id) +' - '+ self.servicio    

class Servicios(models.Model):
    
    servicios_lista = models.ManyToManyField(ServiciosList)             
            
    name = models.CharField(
        'paquete de servicio',
        max_length=25,
        blank=True
    )

    valor_paquete = models.IntegerField(
        'Valor paquete',
        blank=True
    )

    objects = ServiciosManager()   

    def __str__(self):
        return str(self.id)+' - '+str(self.name)+' - '+str(self.valor_paquete)


"""BLANQUEAMIENTOCONCUBETAS='0'
BLANQUEAMIENTOLASER = '1'
CARGAINMEDIATA = '2'
CARILLASCERECCADCAM/PORCELANA = '3'
CORONALIBREDEMETAL = '4'
CORONADESUSTITUCIÓN = '5'
CORONASOBREIMPLANTES = '6'
DIENTEPROVISORIO = '7'
ENDODONCIA = '8'
EXAMENPERIODONTAL = '9'
EXO.TERCERMOLAR/MUELADELJUICIO = '10'
EXODONCIA = '11'
IMPLANTEARCADACOMPLETA(SUP.OINF) = '12'
IMPLANTEPUENTE = '13'
IMPLANTEUNITARIO = '14'
INCRUSTACIONESCEREC = '15'
LIMPIEZADENTAL = '16'
LIMPIEZADENTALPROFUNDA = '17'
ORTODONCIACERÁMICO/INSTALACIÓN = '18'
ORTODONCIARETIRODEBRACKETSPORARCADASINFÉRULA = '19'
ORTODONCIARETIRODEBRACKETSPORARCADACONFÉRULA = '20'
PERNO = '21'
PLANODERELAJACIÓNBRUXISMO = '22'
PROTESISREMOVIBLEPARCIALMETÁLICA = '23'
PROVISORIOSOBREIMPLANTEOCARGAINMEDIATA = '24'
RADIOGRAFÍAPERIAPICAL = '25'
RADIOGRAFÍABITEWING = '26'
RADIOGRAFÍAPANORÁMICA = '27'
RADIOGRAFÍAUNIMAXILAR = '28'
RADIOGRAFÍABIMAXILAR = '29'
RESTAURACIÓNCERVICALCUELLO = '30'
RESTAURACIÓNESTÉTICA = '31'
TRATAMIENTOPULIDORADICULAR(PERIODONTITISSEVERA) = '32'
URGENCIAS = '33'
PRÓTESISPARCIAL = '34'
PRÓTESISTOTAL = '35'
PRÓTESISVALPLASTPARCIALUNILATERAL = '36'
PRÓTESISVALPLASTPARCIALBILATERAL = '37'
PRÓTESISVALPLASTPARCIALCONMETAL = '38'"""



"""BLANQUEAMIENTOCONCUBETAS = '0'
BLANQUEAMIENTO LASER
CARGA INMEDIATA
CARILLAS CEREC CAD CAM /PORCELANA
CORONA LIBRE DE METAL
CORONA DE SUSTITUCIÓN
CORONA SOBRE IMPLANTES
DIENTE PROVISORIO
ENDODONCIA
EXAMEN PERIODONTAL
EXO. TERCER MOLAR/ MUELA DEL JUICIO
EXODONCIA
IMPLANTE ARCADA COMPLETA (SUP. O INF)
IMPLANTE PUENTE
IMPLANTE UNITARIO
INCRUSTACIONES CEREC
LIMPIEZA DENTAL
LIMPIEZA DENTAL PROFUNDA
ORTODONCIA CERÁMICO/INSTALACIÓN
ORTODONCIA RETIRO DE BRACKETS POR ARCADA SIN FÉRULA
ORTODONCIA RETIRO DE BRACKETS POR ARCADA CON FÉRULA
PERNO
PLANO DE RELAJACIÓN BRUXISMO
PROTESIS REMOVIBLE PARCIAL METÁLICA
PROVISORIO SOBRE IMPLANTE O CARGA INMEDIATA
RADIOGRAFÍA PERIAPICAL
RADIOGRAFÍA BITEWING
RADIOGRAFÍA PANORÁMICA
RADIOGRAFÍA UNIMAXILAR
RADIOGRAFÍA BIMAXILAR
RESTAURACIÓN CERVICAL CUELLO
RESTAURACIÓN ESTÉTICA
TRATAMIENTO PULIDO RADICULAR (PERIODONTITIS SEVERA)
URGENCIAS
PRÓTESIS PARCIAL
PRÓTESIS TOTAL
PRÓTESIS VALPLAST PARCIAL UNILATERAL
PRÓTESIS VALPLAST PARCIAL BILATERAL
PRÓTESIS VALPLAST PARCIAL CON METAL
CIRUGÍA PLÁSTICA PERIODONTAL
PULPOTOMÍA
FLUORACIÓN
SELLANTES
CARILLAS COMPOSITE"""

