# Generated by Django 3.1.7 on 2021-05-26 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha vencimiento')),
                ('lote', models.TextField(blank=True, verbose_name='Lote')),
                ('nombre', models.TextField(blank=True, verbose_name='Nombre producto')),
                ('stock', models.PositiveIntegerField(verbose_name='Cantidad de existencias')),
                ('stock_critico', models.PositiveIntegerField(verbose_name='Cantidad en estado critico')),
                ('codigo', models.TextField(blank=True, verbose_name='Codigo producto')),
            ],
            options={
                'verbose_name': 'almacen',
                'verbose_name_plural': ' almacenaje',
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, max_length=250, verbose_name='Tipo de familia')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.almacen')),
            ],
            options={
                'verbose_name': 'sub-producto',
                'verbose_name_plural': 'familia de productos',
            },
        ),
    ]
