# Generated by Django 3.1.7 on 2021-06-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_auto_20210526_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='lote',
            field=models.CharField(blank=True, max_length=15, verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='nombre',
            field=models.CharField(blank=True, max_length=15, verbose_name='Nombre producto'),
        ),
    ]
