# Generated by Django 3.1.7 on 2021-07-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_almacen_empleado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='almacen',
            old_name='empleado',
            new_name='proveedor',
        ),
        migrations.AlterField(
            model_name='almacen',
            name='familia',
            field=models.CharField(blank=True, max_length=50, verbose_name='Familia'),
        ),
    ]
