# Generated by Django 3.1.7 on 2021-06-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_auto_20210612_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, verbose_name='Codigo producto'),
        ),
    ]
