# Generated by Django 3.1.7 on 2021-06-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0004_auto_20210613_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='valor_unitario',
            field=models.PositiveIntegerField(default=1, verbose_name='valor unitario por producto'),
            preserve_default=False,
        ),
    ]
