# Generated by Django 3.1.7 on 2021-06-17 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0005_almacen_valor_unitario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia',
            name='empleado',
        ),
    ]
