# Generated by Django 3.1.7 on 2021-06-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0006_remove_familia_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='num_sale',
            field=models.PositiveIntegerField(default=0, verbose_name='numero de ventas'),
        ),
    ]
