# Generated by Django 3.1.7 on 2021-06-19 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0007_almacen_num_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='almacen',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='almacen',
            name='num_sale',
        ),
        migrations.RemoveField(
            model_name='familia',
            name='familia',
        ),
        migrations.AddField(
            model_name='almacen',
            name='descripcion_breve',
            field=models.CharField(blank=True, max_length=20, verbose_name='Descripcion breve'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='familia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='almacen.familia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='almacen',
            name='valor_unitario',
            field=models.PositiveIntegerField(verbose_name='valor unitario por producto - referencia'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='categoria',
            field=models.CharField(blank=True, max_length=20, verbose_name='sub-tipo'),
        ),
    ]
