# Generated by Django 3.1.7 on 2021-06-22 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0008_auto_20210619_0659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='almacen',
            old_name='stock',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='almacen',
            old_name='descripcion_breve',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='almacen',
            old_name='nombre',
            new_name='nombre_producto',
        ),
        migrations.RenameField(
            model_name='almacen',
            old_name='valor_unitario',
            new_name='precio_unitario',
        ),
    ]
