# Generated by Django 3.1.7 on 2021-06-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0010_auto_20210622_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='almacen',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='almacen',
            name='stock_critico',
        ),
        migrations.AddField(
            model_name='almacen',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Cantidad por producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='almacen',
            name='total',
            field=models.PositiveIntegerField(blank=True, default=True, null=True, verbose_name='Total del producto'),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='codigo',
            field=models.CharField(blank=True, max_length=17, verbose_name='codigo del producto'),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50, verbose_name='Descripcion del producto'),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha vencimiento'),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='nombre_producto',
            field=models.CharField(blank=True, max_length=25, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='precio_unitario',
            field=models.PositiveIntegerField(verbose_name='Precio unitario del producto'),
        ),
    ]
