# Generated by Django 3.1.7 on 2021-06-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_auto_20210616_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='contacto',
            field=models.PositiveIntegerField(default=1, verbose_name='Telefono de contacto'),
            preserve_default=False,
        ),
    ]
